--DROP TABLE public.currspotdeals;
CREATE TABLE currspotdeals
(
NODE "varchar"(60),
DOC_DATE Date,
DOC_TIME Time,
DOC_NO "varchar"(12),
DOC_TYPE_ID "varchar"(12),
SENDER_ID "varchar"(12),
SENDER_NAME "varchar"(30),
RECEIVER_ID "varchar"(12),
REMARKS "varchar"(120),
SIGNAUTHOR "char",
ReportDate Date not null,
FirmId "varchar"(12) not null,
FirmName "varchar"(120) not null,
FirmNameEN "varchar"(120),
ClearingFirmId "varchar"(12) not null,
ClearingFirmName "varchar"(120) not null,
ClearingFirmNameEN "varchar"(120),
ExtSettleCode "varchar"(20) not null,
ExtTradeCode "varchar"(20) not null,
ExtTradeCodeType "varchar"(10) not null,
AddSession "varchar"(1) not null,
SessionName "varchar"(30) not null,
SessionNameEN "varchar"(30) not null,
CurrencyId "varchar"(4) not null,
CurrencyName "varchar"(30) not null,
CurrencyNameEN "varchar"(30),
CoCurrencyId "varchar"(4) not null,
CoCurrencyName "varchar"(30) not null,
CoCurrencyNameEN "varchar"(30),
SecurityId "varchar"(12) not null,
SecShortName "varchar"(10) not null,
FaceValue Numeric not null,
SettleDate Date not null,
TradeGroup "varchar"(1) not null,
MainSecurityId "varchar"(12)not null,
MainSecShortName "varchar"(10) not null,
TradeNo	Numeric not null,
BuySell	"varchar"(1) not null,
OrderNo	Numeric not null,
TradeDeriv "varchar"(1) not null,
TradeTime Time not null,
TradeType "varchar"(1) not null,
Decimals Numeric not null,
Price Numeric not null,
Quantity Numeric not null,
Value Numeric not null,
CPFirmId "varchar"(12),
Period "varchar"(1) not null,
SettleCode "varchar"(12) not null,
UserId "varchar"(12) not null,
UserExchangeId "varchar"(4) not null,
BrokerRef "varchar"(20),
ExtRef "varchar"(12),
ExchComm Numeric,
ITSComm Numeric,
ClrComm Numeric,
SumComm Numeric,
TrdAccId "varchar"(12) not null,
ClientCode "varchar"(12),
Details	"varchar"(20),
SubDetails "varchar"(20),
RepoTradeNo Numeric,
BoardId	"varchar"(4) not null,
BoardName "varchar"(30) not null,
BoardNameEN "varchar"(30)
)