--DROP TABLE public.futdeals;
CREATE TABLE public.futdeals
(id_deal numeric(10),
isin char(25),
price numeric(16,5),
vol numeric(10),
kod_sell char(7),
kod_buy	char(7),
date char(10),
time char(8),
profit_usd numeric(20,4),
type numeric(2),
var_marg_b numeric(16,2),
var_marg_s numeric(16,2),
user_sell char(20),
user_buy char(20),
no_buy numeric(15),
no_sell	numeric(15),
fee_buy	numeric(16,2),
fee_sell numeric(16,2),
date2 Date,
comm_buy char(20),
comm_sell char(20),
du_buy	numeric(1),
du_sell	numeric(1),
fee_ns_b numeric(16, 2),
fee_ns_s numeric(16, 2),
price_rur numeric(16, 5),
ext_id_b numeric(11),
ext_id_s numeric(11),
date_clr date,
repo_id	numeric(11),
fee_ex_b numeric(16,2),
vat_ex_b numeric(16,2),
fee_cc_b numeric(16,2),
vat_cc_b numeric(16,2),
fee_ex_s numeric(16,2),
vat_ex_s numeric(16,2),
fee_cc_s numeric(16,2),
vat_cc_s numeric(16,2),
id_mult	numeric(10),
signs numeric(11)
)
