--DROP TABLE public.stockdeals;
CREATE TABLE public.stockdeals
(
NODE "varchar"(60),
DOC_DATE Date,
DOC_TIME Time,
DOC_NO "varchar"(12),
DOC_TYPE_ID "varchar"(12),
SENDER_ID "varchar"(12),
SENDER_NAME "varchar"(30),
RECEIVER_ID "varchar"(12),
REMARKS "varchar"(120),
ReportDate Date not null,
Weekday "varchar"(12) not null,
MainFirmId "varchar"(12) not null,
FirmID "varchar"(12) not null,
CurrencyId "varchar"(4) not null,
CurrencyName "varchar"(30) not null,
InfType Numeric(1,0) not null,
ClearingType "varchar"(1),
Session Numeric(1,0) not null,
SettleDate Date not null,
InstrType "varchar"(1),
BoardId	"varchar"(4) not null,
BoardName "varchar"(30) not null,
SecurityId "varchar"(12) not null,
ISIN "varchar"(12),
SecShortName "varchar"(10) not null,
PriceType "varchar"(4),
RecNo Numeric(11,0) not null,
TradeNo Numeric(20,0) not null,
TradeDate Date not null,
TradeTime Time not null,
BuySell	"varchar"(1) not null,
SettleCode "varchar"(12) not null,
Decimals Numeric(1,0) not null,
Price Numeric(20,6),
Quantity Numeric(20,0) not null,
Value Numeric(20,2),
DepoRate Numeric(20,6),
AccInt Numeric(20,2),
Amount Numeric(20,2),
Balance Numeric(20,0),
Sum1 Numeric(20,2),
Sum2 Numeric(20,2),
ExchComm Numeric(20,2),
ClrComm Numeric(20,2),
ITSComm Numeric(20,2),
TrdAccId "varchar"(12) not null,
ClientDetails "varchar"(41),
CPFirmId "varchar"(12),
CPFirmShortName "varchar"(30),
Price2 Numeric(20,6),
Payoff Numeric(20,6),
RepoPart Numeric,
RepoPeriod Numeric(11,0),
ReportNo Numeric(20,0),
ReportTime Time,
SettleTime Time,
ClientCode "varchar"(12),
DueDate Date not null,
Type Numeric,
SystemRef "varchar"(12)
)